# Site settings
title: HBTech - Riqualificazione Energetica
description: Servizi professionali di riqualificazione energetica, efficientamento, impianti, isolamento, fotovoltaico, domotica, consulenza e ingegneria.
url: "https://${{ github.repository_owner }}.github.io"
baseurl: "/hbt2"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - .gitignore

# Include only necessary files
include:
  - _pages
  - _posts
  - _layouts
  - _includes
  - _sass
  - _config.yml
  - index.html
  - contatti.html
  - richiesta.html
  - styles_Version6.css
  - images
  - robots.txt

# Performance optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  profile: false
  startings: [html, head, body]

# Sitemap settings
sitemap:
  changefreq: weekly
  priority: 0.8
  lastmod: true

# SEO settings
author:
  name: HBTech Engineering & SRLs
  email: info@hbtech.it
  bio: Servizi di riqualificazione energetica
  location: Puglia, Italia
  links:
    - label: Email
      icon: fas fa-envelope
      url: mailto:info@hbtech.it
    - label: Telefono
      icon: fas fa-phone
      url: tel:+390000000000

# Social media
social:
  name: HBTech
  links:
    - https://github.com/${{ github.repository_owner }}/hbt2

# Analytics (opzionale)
analytics:
  provider: google
  google:
    tracking_id: # Inserisci il tuo Google Analytics ID se lo hai

# Comments (opzionale)
comments:
  provider: # Inserisci il provider dei commenti se lo vuoi

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Timezone
timezone: Europe/Rome

# Encoding
encoding: utf-8

# Safe mode
safe: true

# Future posts
future: false

# Show drafts
show_drafts: false

# Limit posts
limit_posts: 0

# Excerpt separator
excerpt_separator: "\n\n"

# Gems
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-compress-html
